[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#5D8C2E"
backgroundColor = "#1a1f1a"
secondaryBackgroundColor = "#2d3a25"
textColor = "#f0f0d8"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
