[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#3B82F6"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
